version: "3"
services:
  jupyterlab:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - type: bind
        source: "../code-ch01"
        target: "/home/jovyan/work/code-ch01"
      - type: bind
        source: "../code-ch02"
        target: "/home/jovyan/work/code-ch02"
    environment:
      NB_UID: 8888
      GRANT_SUDO: "yes"
    command: start.sh jupyter lab